spring:
  application:
    name: PSpringUI

server:
  port: ${PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include: "refresh"

##datasource:
uri:
  gateway: http://gateway_url/api
  registry: http://PSPRINGAPI



management.endpoints.web.exposure.include: "refresh"